import type { Metadata } from 'next'

import { Toaster } from 'react-hot-toast'

import PrelineScript from '@/loaders/Preline'
import { QueryProvider } from '@/providers/QueryProvider'
import { roboto } from '@/theme'

import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="pt-BR">
			<QueryProvider>
				<body className={`h-screen w-screen ${roboto.className}`}>
					{children}
					<Toaster position="top-right" toastOptions={{ duration: 3000 }} />
				</body>
			</QueryProvider>
			<PrelineScript />
		</html>
	)
}
