import type { Metadata } from 'next'

import './globals.css'
import PrelineScript from '@/loaders/Preline'
import { roboto } from '@/theme'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="pt-BR">
			<body className={`h-screen w-screen ${roboto.className}`}>
				{children}
			</body>
			<PrelineScript />
		</html>
	)
}
